-- fireball_d
-- small_smoke
-- magicmissile
-- exp_fire
-- beamlaser_blue_hit_200

return {
  ["fireball_d"] = {
    fire = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:EXP_FIRE]],
        pos                = [[0, 0, 0]],
      },
    },
    takeoff1 = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 3,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.95,
        airlos             = 0,
        colormap           = [[1 0.2 0 0.1 0.04 0.04 0.04 0.2    0 0 0 0.01]],
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.01, 0]],
        numparticles       = 20,
        particlelife       = 40,
        particlelifespread = 0,
        particlesize       = [[2r4]],
        particlesizespread = 1,
        particlespeed      = [[5r3]],
        particlespeedspread = 0,
        pos                = [[0, 3, 0]],
        sizegrowth         = .3,
        sizemod            = 0.5,
        texture            = [[foam]],
      },
    },
  },

  ["small_smoke"] = {
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        airdrag            = 0.96,
        colormap           = [[0.05 0.05 0.05 0.2  0 0 0 0.001]],
        directional        = false,
        emitrot            = 20,
        emitrotspread      = 10,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.0001, 0]],
        numparticles       = 30,
        particlelife       = 30,
        particlelifespread = 70,
        particlesize       = 5,
        particlesizespread = 1,
        particlespeed      = 0,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1.01,
        sizemod            = 0.8,
        texture            = [[smoke_orange]],
      },
    },
  },

  ["magicmissile"] = {
    usedefaultexplosions = false,
    effect1 = {
      air                = true,
      class              = [[explspike]],
      count              = 5,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = .15,
        color              = [[0.2, 0.3, 1.0]],
        dir                = [[-6r9, -6r9, -6r9]],
        length             = 7,
        lengthgrowth       = -.1,
        width              = 11,
      },
    },
  },

  ["exp_fire"] = {
    fire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        airdrag            = 0.93,
        colormap           = [[1 1 1 0.25   1 0.8 0.5 0.25   0.08 0.08 0.08 0.3    0 0 0 0.001]],
        directional        = false,
        emitrot            = 52,
        emitrotspread      = 38,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.001, 0]],
        numparticles       = 22,
        particlelife       = 20,
        particlelifespread = 40,
        particlesize       = 20,
        particlesizespread = 10,
        particlespeed      = 1.5,
        particlespeedspread = 5.5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1,
        sizemod            = 0.2,
        texture            = [[smoke_orange]],
      },
    },
    smoke = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        delay              = 5,
        explosiongenerator = [[custom:small_smoke]],
        pos                = [[0, 0, 0]],
      },
    },
  },

  ["beamlaser_blue_hit_200"] = {
    usedefaultexplosions = false,
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.02,
        color              = [[0.75,0.75,1]],
        dir                = [[-4 r4 r4, 1 r4, -4 r4 r4]],
        length             = 1,
        lengthgrowth       = 1,
        width              = 4,
      },
    },
    sparks = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 1 1 0.01  1 0.75 0 0.01  0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 4,
        particlelife       = 20,
        particlelifespread = 5,
        particlesize       = 4,
        particlesizespread = 2,
        particlespeed      = 4,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
  },

}

